version: '3.9'

services:
  bac_vuln:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=bac_db_vuln
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - bac_db_vuln

  bac_db_vuln:
    image: postgres:12
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
